---
title: "Fi3_sup3_hemi"
author: "Frederic Theunissen & Lily Xue Gong"
date: "5/28/2022"
  pdf_document: default
html_document: default
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Loading up the depencies

```{r libraries}
library(nnet)   # for multinom()
library(rstatix) # for multinom_test()

library(dplyr)  # for filter()

library(ggplot2) # for the boxplot()
library(ggpubr)

library(lme4) # for lmer
library(kableExtra)

```

## If thirdOrder phonemic perf is statistically different across left vs right hemisphere in WB, and other ROI:

## conclusion: NO

```{r third order simple comparison through different ROIs}

# Read the data for thirdOrder vs semantic
data_hemi_thirdSem <- read.csv("../stats_data/df_perfMean_thirdSem_hemi.csv")

# Clean up
data_hemi_thirdSem <- na.omit(data_hemi_thirdSem)
data_hemi_thirdSem <- subset(data_hemi_thirdSem, select = -c(X))

rois_names <- unique(data_hemi_thirdSem$rois)
manual_p_adjust_coefficient <-  length(rois_names)


for (r in rois_names){
  print(r)
  data_sub_hemi <- filter(data_hemi_thirdSem, rois == r & models == "thirdOrder")
  data_sub_hemi <- subset(data_sub_hemi, select = -c(rois))
  attach(data_sub_hemi)
  models <-factor(models)
  levels(models) <- c("thirdOrder",ordered=TRUE)
  detach(data_sub_hemi)
  
  model_thirdOrder_hemi_full <- lmer (performance ~ hemis + (1 | subjects), data_sub_hemi)
  model_thirdOrder_noInt <- lmer (performance ~ 1 + (1 | subjects), data_sub_hemi)
  
  a_thirdOrder_hemis<-anova(model_thirdOrder_hemi_full, model_thirdOrder_noInt, p.adj = "bonf")
  
  print(sprintf('Likelihood Ratio Test  left  vs right hemi in %s: ChiSq(%d) = %.2f p=%.2g (manual adjusted p=%.2g)', r, a_thirdOrder_hemis$Df[2], a_thirdOrder_hemis$Chisq[2], a_thirdOrder_hemis$Pr[2], a_thirdOrder_hemis$Pr[2]*manual_p_adjust_coefficient))
}


```



```{r dataload phonemes, echo=FALSE}

# Read the data for single, diphone vs triphone
data_hemi_phns<- read.csv("../stats_data/df_perfMean_phns_hemi.csv")

# Clean up
data_hemi_phns <- na.omit(data_hemi_phns)
data_hemi_phns <- subset(data_hemi_phns, select = -c(X))

# Split into 3 different data frames
dataLC_phns_hemi <- filter(data_hemi_phns, rois != "WB" & rois != "Broca" & models != "semantic")
attach(dataLC_phns_hemi)
rois <-factor(rois)
levels(rois) <- c("ACunique", "STG", "STS", "LTCunique")
models <-factor(models)
levels(models) <- c("single","diphone", "triphone", ordered=TRUE)
detach(dataLC_phns_hemi)

```

## check interaction fo reach roi for single vs diphone vs triphone differnce


```{r interaction for phns, echo=FALSE}

rois_names <- unique(data_hemi_phns$rois)
manual_p_adjust_coefficient <-  length(rois_names)

for (r in rois_names){
  print(r)
  data_sub_phns <- filter(data_hemi_phns, rois == r)
  data_sub_phns <- subset(data_sub_phns, select = -c(rois))
  attach(data_sub_phns)
  models <-factor(models)
  levels(models) <- c("single", "diphone", "triphone",rdered=TRUE)
  detach(data_sub_phns)

  bxp <-
    ggboxplot(
      data_sub_phns, x = "hemis", y = "performance",
      color = "models", color_order = c("thirdOrder", "semantic"),
      palette = "jco")
  bxp
  
  model_phns_hemi_full <- lmer (performance ~ models*hemis + (1 | subjects), data_sub_phns)
  model_phns_noInt <- lmer (performance ~ models + hemis + (1 | subjects), data_sub_phns)
  
  a_phns_hemis<-anova(model_phns_hemi_full, model_phns_noInt, p.adj = "bonf")
  
  print(sprintf('Likelihood Ratio Test (single vs diphone vs triphone) for hemisphere across %s: ChiSq(%d) = %.2f p=%.2g', r, a_phns_hemis$Df[2], a_phns_hemis$Chisq[2], a_phns_hemis$Pr[2]))
  
}

```



##  Temporal Cortex Interaction

```{r  temporal cortex for phns, echo=FALSE}

bxp <-
  ggboxplot(
    dataLC_phns_hemi, x = "rois", y = "performance",
    color = "hemis", color_order = c("single", "diphone", "triphone", ordered=TRUE),
    shape = "models",
    palette = "jco")
bxp


model_phns_superfull <- lmer (performance ~ rois*models*hemis + (1 | subjects), dataLC_phns_hemi)
model_phns_noIntHemi <- lmer (performance ~ rois + models +  models*rois + (1 | subjects), dataLC_phns_hemi)

a_phns_hemiTC<-anova(model_phns_superfull, model_phns_noIntHemi, p.adj = "bonf")

print(sprintf('Likelihood Ratio Test (single vs diphone vs triphone) for hemisphere across TC: ChiSq(%d) = %.2f p=%.2g', a_phns_hemiTC$Df[2], a_phns_hemiTC$Chisq[2], a_phns_hemiTC$Pr[2]))

```


## Posthoc test for each ROI

```{r posthoc test for each ROI}
rois_name_phns <- unique(data_hemi_phns$rois)
nrois_phns <- length(rois_name_phns)

hemi_name_phns <- unique(data_hemi_phns$hemis)
nhemi_phns <- length(hemi_name_phns)

manual_p_adjust_coefficient <-  nrois_phns*12

for (irois_phns in 1:nrois_phns) {
   print(rois_name_phns[irois_phns])
  for (ihemi_phns in 1:nhemi_phns){
   
    data_sub<- filter(data_hemi_phns, rois == rois_name_phns[irois_phns] & hemis == hemi_name_phns[ihemi_phns])
    
    ## paired one way anova test 
    res.aov <- aov(performance ~ models, data = data_sub, p.adjust.methods = "bonferroni")
    gofit.res <- summary(res.aov)
    tukey.res <- TukeyHSD(res.aov, p.adjust.method = "bonferroni")
    
    pval <- gofit.res[[1]]["Pr(>F)"][[1]][[1]]
    sin_di_diff <- data.frame(tukey.res$models)["diff"][[1]][1]
    sin_di_p <- data.frame(tukey.res$models)["p.adj"][[1]][1]
    tri_di_diff <- data.frame(tukey.res$models)["diff"][[1]][2]
    tri_di_p <- data.frame(tukey.res$models)["p.adj"][[1]][2]
    tri_sin_diff <- data.frame(tukey.res$models)["diff"][[1]][3]
    tri_sin_p <- data.frame(tukey.res$models)["p.adj"][[1]][2]
  
    df <- gofit.res[[1]]["Df"][[1]][[1]]
    stats <- gofit.res[[1]]["F value"][[1]][[1]]
    print(sprintf('      Hemi %s region %s: F(%d)= %.2f (p=%.2g, manual adjusted p=%.2g): sin_di_diff diff =  %.3f (p.adj = %.2g, manual adjusted p=%.2g),  tri_di_diff = %.3f (p.adj = %.2g, manual adjusted p=%.2g), tri_sin_diff= %.3f (p.adj = %.2g, manual adjusted p=%.2g)',  hemi_name_phns[ihemi_phns], rois_name_phns[irois_phns], df, stats, pval, pval*manual_p_adjust_coefficient, sin_di_diff, sin_di_p, sin_di_p*manual_p_adjust_coefficient, tri_di_diff, tri_di_p, tri_di_p*manual_p_adjust_coefficient, tri_sin_diff, tri_sin_p, tri_sin_p*manual_p_adjust_coefficient))
  }
}

```



```{r dprime calc: single vs diphone vs  triphone, echo=FALSE}




dprime_sum_phns <- array(0, dim=c(nrois_phns, nhemi_phns))
dprime_sem_phns <- array(0, dim=c(nrois_phns, nhemi_phns))

for (ihemi_phns in 1:nhemi_phns){
  for (irois_phns in 1:nrois_phns) {
  
  data_sub_phns <- filter(data_hemi_phns, rois == rois_name_phns[irois_phns] & hemis == hemi_name_phns[ihemi_phns])
  data_sub_phns <- subset(data_sub_phns, select = -c(rois))
  attach(data_sub_phns)
  models <-factor(models)
  levels(data_sub_phns) <- c("single", "diphone", "triphone", ordered=TRUE)
  detach(data_sub_phns)
  
  model_phns_features <- lmer (performance ~ models + (1 | subjects), data_sub_phns)

  model_phns_features_summary <- summary(model_phns_features)
  
  pred_std <- as.data.frame(model_phns_features_summary$varcor)$sdcor[1]
  pred_diff_sinDi <- as.data.frame(model_phns_features_summary$coefficients)$Estimate[2]
  pred_diff_sinTri <- as.data.frame(model_phns_features_summary$coefficients)$Estimate[3]
  pred_se_sinDi <- as.data.frame(model_phns_features_summary$coefficients)$Std[2]
  pred_se_sinTri <- as.data.frame(model_phns_features_summary$coefficients)$Std[3]
  
  
  dprime_sum_phns[irois_phns, ihemi_phns] <- (pred_diff_sinDi/pred_std + pred_diff_sinTri/pred_std)/2
  dprime_sem_phns[irois_phns, ihemi_phns] <- sqrt((pred_se_sinDi/pred_std)^2 + (pred_se_sinTri/pred_std)^2)/2

  print(sprintf('Cohen dprime for single vs diphone vs triphone  for %s for %s:  %.3f +- %.3f ', rois_name_phns[irois_phns], hemi_name_phns[ihemi_phns],  -dprime_sum_phns[irois_phns, ihemi_phns], 2*dprime_sem_phns[irois_phns, ihemi_phns]))
  

}
}



```



```{r Individual summary table generation phns, echo=FALSE}
subject.names <- unique(data_hemi_phns$subjects)
rois_name <- unique(data_hemi_phns$rois)
hemis_name <- unique(data_hemi_phns$hemis)
nrois <- length(rois_name)
nsubjects <- length(subject.names)
sin_mean <- array(dim=c(nsubjects, nrois,2))
di_mean <- array(dim=c(nsubjects, nrois,2))
tri_mean <- array(dim=c(nsubjects, nrois,2))
dprime_ind_phns <- array(dim=c(nsubjects, nrois,2))

i <- 1
for (sname in subject.names) {
  for (irois in 1:nrois) {
    for (ihemis in 1:2){
      data.subject <- data_hemi_phns[data_hemi_phns$subjects==sname & data_hemi_phns$rois==rois_name[irois] & data_hemi_phns$hemis == hemis_name[ihemis], ]
    sin_mean[i,irois,ihemis] <- mean(na.omit(data.subject[data.subject$models == "single",]$performance))
    di_mean[i,irois,ihemis] <- mean(na.omit(data.subject[data.subject$models == "diphone",]$performance))
    tri_mean[i,irois,ihemis] <- mean(na.omit(data.subject[data.subject$models == "triphone",]$performance))
    
    std_diSin <- sd(na.omit(data.subject[data.subject$models == "diphone",]$performance) - na.omit(data.subject[data.subject$models == "single",]$performance))
    std_diTri <- sd(na.omit(data.subject[data.subject$models == "diphone",]$performance) - na.omit(data.subject[data.subject$models == "triphone",]$performance))
    
    sin_mean[i,irois,ihemis] [is.nan(sin_mean[i,irois,ihemis])] <- 0
    di_mean[i,irois,ihemis] [is.nan(di_mean[i,irois,ihemis])] <- 0
    tri_mean[i,irois,ihemis] [is.nan(tri_mean[i,irois,ihemis])] <- 0
    
    
    if (is.na(std_diSin) || is.na(std_diTri)){
      diprime_diSin <- (di_mean[i,irois,ihemis] - sin_mean[i,irois,ihemis])
      diprime_diTri <- (di_mean[i,irois,ihemis] - tri_mean[i,irois,ihemis])
    }
    else{
      diprime_diSin <- (di_mean[i,irois,ihemis] - sin_mean[i,irois,ihemis])/std_diSin
      diprime_diTri <- (di_mean[i,irois,ihemis] - tri_mean[i,irois,ihemis])/std_diTri
    }
    dprime_ind_phns[i,irois,ihemis] <- (diprime_diSin + diprime_diTri)/2
    }
  }
  i <- i + 1
}


subjectTable_phns_dprime <- data.frame(subject=1:nsubjects, 
                           AC_dprimeL=dprime_ind_phns[,2,1], 
                           AC_dprimeR=dprime_ind_phns[,2,2], 
                           STG_dprimeL=dprime_ind_phns[,3,1], 
                           STG_dprimeR=dprime_ind_phns[,3,2],
                           STS_dprimeL=dprime_ind_phns[,4,1], 
                           STS_dprimeR=dprime_ind_phns[,4,2], 
                           LTC_dprimeL=dprime_ind_phns[,5,1], 
                           LTC_dprimeR=dprime_ind_phns[,5,2], 
                           Broca_dprimeL=dprime_ind_phns[,6,1],
                           Broca_dprimeR=dprime_ind_phns[,6,2],
                           WB_dprimeL=dprime_ind_phns[,1,1],
                           WB_dprimeR=dprime_ind_phns[,1,2]
                           )


```


```{r save kable}

#kable(subjectTable_phns, caption=" Mean prediction performance across subjects and brain regions", format.args=list(digits = 2))

kable(subjectTable_phns[,c(1,2,3,4,5,6,7,8,9,10,11, 12, 13)], caption="Mean prediction performance across subjects and brain regions: Single Vs Diphone VS Triphone ", format.args=list(digits = 2))

kable(subjectTable_phns[,c(1,14,15,16,17,18,19,20,21,22,23,24,25)], caption="Mean prediction performance across subjects and brain regions: Single Vs Diphone VS Triphone ", format.args=list(digits = 2))

kable(subjectTable_phns[,c(1,26,27,28,29,30,31,32,33,34,35, 36, 37)], caption="Mean prediction performance across subjects and brain regions: Single Vs Diphone VS Triphone ", format.args=list(digits = 2))

kable(subjectTable_phns[,c(1,38,39,40,41,42,43,44,45,46,47,48,49)], caption="Mean prediction performance across subjects and brain regions: Single Vs Diphone VS Triphone ", format.args=list(digits = 2))

```


