---
title: "fig4_diphnCate"
author: "Lily"
date: "1/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## R Loading up the depencies

```{r libraries}
library(knitr)
library(nnet)   # for multinom()
library(rstatix) # for multinom_test()

library(dplyr)  # for filter()

library(ggplot2) # for the boxplot()
library(ggpubr)

library(PairedData) # for paired ttest
library(lme4) # for lmer

library(kableExtra)

```


```{r dataload norm , echo=FALSE}

# Read the data 
data_diphnCat_normed <- read.csv("./diphnCate_perf_normed_df.csv")

# Clean up
data_diphnCat_normed[data_diphnCat_normed<=0] = NA
data_diphnCat_normed <- na.omit(data_diphnCat_normed)
data_diphnCat_normed <- subset(data_diphnCat_normed, select = -c(X))


bxp <-
  ggboxplot(
    data_diphnCat_normed, x = "models", y = "performance",
     color_order = c("shortWords", "bg", "res"),
    palette = "jco")
bxp

## compute stats among three diphn categories
data_diphnCat_normed_cate <- lmer (performance ~ models + (1 | subjects), data_diphnCat_normed)
data_diphnCat_normed_null <- lmer (performance ~ 1 + (1 | subjects), data_diphnCat_normed)

a_diphn_normed_cate<-anova(data_diphnCat_normed_null, data_diphnCat_normed_cate, p.adj = "bonf")

print(sprintf('Likelihood Ratio Test for diphn cate normed only: ChiSq(%d) = %.2f p=%.2g', a_diphn_normed_cate$Df[2], a_diphn_normed_cate$Chisq[2], a_diphn_normed_cate$Pr[2]))

## posthoc test
res_aov <- aov(performance ~ models, data_diphnCat_normed)
posthoc_res <- TukeyHSD(res_aov, p.adj = "bonf")

```

```{r individual subject stats}

## create sum table
data_diphnCat_normed_prep <- data_diphnCat_normed
data_diphnCat_normed_prep[data_diphnCat_normed_prep == "shortWords"] <- "Words"
data_diphnCat_normed_prep[data_diphnCat_normed_prep == "bg"] <- "Beginning"
data_diphnCat_normed_prep[data_diphnCat_normed_prep == "res"] <- "Residual"

subjects_all <- unique(data_diphnCat_normed_prep$subjects)

print('   Per subject:')
for (s in subjects_all) {
  print(s)
  data_sub <- data_diphnCat_normed_prep[data_diphnCat_normed_prep$subjects == s, ]
  res.aov <- aov(performance ~ models, data = data_sub, p.adjust.method = "bonferroni")
  gofit.res <- summary(res.aov)
  tukey.res <- TukeyHSD(res.aov, p.adjust.method = "bonferroni")
  pvalSubject <- gofit.res[[1]]["Pr(>F)"][[1]][[1]]
  res_beg_diff <- data.frame(tukey.res$models)["diff"][[1]][1]
  res_beg_p <- data.frame(tukey.res$models)["p.adj"][[1]][1]
  word_beg_diff <- data.frame(tukey.res$models)["diff"][[1]][2]
  word_beg_p <- data.frame(tukey.res$models)["p.adj"][[1]][2]
  word_res_diff <- data.frame(tukey.res$models)["diff"][[1]][3]
  word_res_p <- data.frame(tukey.res$models)["p.adj"][[1]][2]

  df <- gofit.res[[1]]["Df"][[1]][[1]]
  stats <- gofit.res[[1]]["F value"][[1]][[1]]
  print(sprintf('      Subject %s: F(%d)= %.2f p=%.2g: res_beg diff =  %.3f (p.adj = %.3f),  word_beg_diff = %.3f (p.adj = %.3f), word_res_diff= %.3f (p.adj = %.3f)',  s, df, stats, pvalSubject, res_beg_diff, res_beg_p, word_beg_diff, word_beg_p, word_res_diff, word_res_p))
}
```




```{r dataload norm summary table, echo=FALSE}


diphnCate_normed_sum_table <- with(data_diphnCat_normed_prep, tapply(performance, list(subjects, models), mean))
diphnCate_normed_sum_df <- data.frame(diphnCate_normed_sum_table)

table_tmp <- array(dim=c(nsubjects+2,3)) 
table_tmp <- diphnCate_normed_sum_df

table_tmp[12,] <- colMeans(diphnCate_normed_sum_df)
table_tmp[13,1] <- sd(diphnCate_normed_sum_df[,1])/sqrt(nsubjects)
table_tmp[13,2] <- sd(diphnCate_normed_sum_df[,2])/sqrt(nsubjects)
table_tmp[13,3] <- sd(diphnCate_normed_sum_df[,3])/sqrt(nsubjects)


sub_label <- array(dim=nsubjects+2)
sub_label[1:11] <- 1:nsubjects
sub_label[12] <- "average"
sub_label[13] <- "sem"

subjectTable <- data.frame(subject=sub_label, 
                           Words=table_tmp[,3], 
                           Beginning=table_tmp[,1],
                           Residual=table_tmp[,2]
                           )
# kable(diphnCate_normed_sum_df[,c(1, 2, 3)], caption="Mean prediction performance across subjects for shortWords, word beginnings (bg) and diphone residuals (res) ", format.args=list(digits = 2))

subjectTable %>%
  kbl(caption = "Diphone Category", digits = 3) %>%
  kable_classic_2(full_width = F, html_font = "Cambria") %>%
  row_spec(1:11, bold = T, color = "white", background = "#D7261E")%>%
  save_kable("./Fig4_sup2_diphnCate_meanPerf.png")

```


```{r dataload normed mean, echo=FALSE}

# Read the data 
data_diphnCat_normed_mean <- read.csv("./diphnCate_perfMean_normed_df.csv")

# Clean up
data_diphnCat_normed_mean <- na.omit(data_diphnCat_normed_mean)
data_diphnCat_normed_mean <- subset(data_diphnCat_normed_mean, select = -c(X))


bxp <-
  ggboxplot(
    data_diphnCat_normed_mean, x = "models", y = "performance",
     color_order = c("shortWords", "bg", "res"),
    palette = "jco")
bxp

## compute stats among three diphn categories
data_diphnCat_normed_mean_cate <- lmer (performance ~ models + (1 | subjects), data_diphnCat_normed_mean)
data_diphnCat_normed_mean_null <- lmer (performance ~ 1 + (1 | subjects), data_diphnCat_normed_mean)

a_diphn_normed_mean_cate<-anova(data_diphnCat_normed_mean_null, data_diphnCat_normed_mean_cate, p.adj = "bonf")

print(sprintf('Likelihood Ratio Test for diphn cate normed only: ChiSq(%d) = %.2f p=%.2g', a_diphn_normed_mean_cate$Df[2], a_diphn_normed_mean_cate$Chisq[2], a_diphn_normed_mean_cate$Pr[2]))

## posthoc test
res_aov_normed_mean <- aov(performance ~ models, data_diphnCat_normed_mean)
posthoc_res_normed_mean <- TukeyHSD(res_aov_normed_mean, p.adj = "bonf")

```



```{r second way of anova }

res.aov <- anova_test(data = data_diphnCat_normed_mean, dv = performance, wid = subjects, within = models)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- data_diphnCat_normed_mean %>%
  pairwise_t_test(
    performance ~ models, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

```
